//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NL.Server.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NL.Server.Configuration.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}, {1}] Connection with client was initiated..
        /// </summary>
        internal static string ClientConnected {
            get {
                return ResourceManager.GetString("ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}, {1}] Connection with client was ended..
        /// </summary>
        internal static string ClientDisconnected {
            get {
                return ResourceManager.GetString("ClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}, {1}] Connection with client was abnormally terminated..
        /// </summary>
        internal static string ClientTerminated {
            get {
                return ResourceManager.GetString("ClientTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}, {1}] Transmitted: {2}..
        /// </summary>
        internal static string ClientTransmitted {
            get {
                return ResourceManager.GetString("ClientTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLS;Clears the console of all text with exception of the command line.;DISABLECL;Removes and disables the command line from the console. It is not possible to re-enable the command line after this command has been executed without restarting the console.;DCIP &lt;IP&gt;;Disconnects all connections with the IP address from all servers.;DCSERVER &lt;PORT&gt;;Closes all connections from the server and disables it from accepting any further connections.;CSERVER &lt;PORT&gt;;Reconnects the server assigned to the target port, acce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded beep settings..
        /// </summary>
        internal static string ConfigBeepLoadComplete {
            get {
                return ResourceManager.GetString("ConfigBeepLoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load beep settings..
        /// </summary>
        internal static string ConfigBeepLoadFailed {
            get {
                return ResourceManager.GetString("ConfigBeepLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded startup commands..
        /// </summary>
        internal static string ConfigStartUpLoadComplete {
            get {
                return ResourceManager.GetString("ConfigStartUpLoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller does not exist..
        /// </summary>
        internal static string ControllerDoesNotExist {
            get {
                return ResourceManager.GetString("ControllerDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;help&apos; for a list of available commands..
        /// </summary>
        internal static string HelpPrompt {
            get {
                return ResourceManager.GetString("HelpPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address given..
        /// </summary>
        internal static string InvIPAddress {
            get {
                return ResourceManager.GetString("InvIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of arguments..
        /// </summary>
        internal static string InvNoOfArgs {
            get {
                return ResourceManager.GetString("InvNoOfArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port number given..
        /// </summary>
        internal static string InvPort {
            get {
                return ResourceManager.GetString("InvPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connection(s) terminated..
        /// </summary>
        internal static string IPDisconnected {
            get {
                return ResourceManager.GetString("IPDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nlconsole..
        /// </summary>
        internal static string NLConsolePrompt {
            get {
                return ResourceManager.GetString("NLConsolePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neural Link.
        /// </summary>
        internal static string NLConsoleTitle {
            get {
                return ResourceManager.GetString("NLConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port {0} is unavailable..
        /// </summary>
        internal static string PortUnavailable {
            get {
                return ResourceManager.GetString("PortUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server was abnormally terminated on port {0}: {1}..
        /// </summary>
        internal static string ServerAbnormallyTerminated {
            get {
                return ResourceManager.GetString("ServerAbnormallyTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added to port {1}..
        /// </summary>
        internal static string ServerAdded {
            get {
                return ResourceManager.GetString("ServerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is already connected..
        /// </summary>
        internal static string ServerAlreadyConnected {
            get {
                return ResourceManager.GetString("ServerAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} online and listening on port {1}..
        /// </summary>
        internal static string ServerConnected {
            get {
                return ResourceManager.GetString("ServerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disconnected from port {1}..
        /// </summary>
        internal static string ServerDisconnected {
            get {
                return ResourceManager.GetString("ServerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A server does not exist on port {0}..
        /// </summary>
        internal static string ServerDoesNotExistOnPort {
            get {
                return ResourceManager.GetString("ServerDoesNotExistOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A server already exists on port {0}..
        /// </summary>
        internal static string ServerExistsOnPort {
            get {
                return ResourceManager.GetString("ServerExistsOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not connected..
        /// </summary>
        internal static string ServerNotConnected {
            get {
                return ResourceManager.GetString("ServerNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time taken to hash: {0} seconds.
        /// </summary>
        internal static string TimeTakenToHash {
            get {
                return ResourceManager.GetString("TimeTakenToHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognised action..
        /// </summary>
        internal static string UnrecognisedAction {
            get {
                return ResourceManager.GetString("UnrecognisedAction", resourceCulture);
            }
        }
    }
}
